import { Ionicons } from "@expo/vector-icons";
import { ResizeMode, Video } from "expo-av";
import { useEffect, useRef, useState } from "react";
import {
  ActivityIndicator,
  Dimensions,
  SafeAreaView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";

const { width: screenWidth } = Dimensions.get("window");

const VideoEditorScreen = ({ navigation, route }) => {
  const { videoUri } = route.params;
  const videoRef = useRef(null);

  const [isPlaying, setIsPlaying] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [videoInfo, setVideoInfo] = useState(null);
  const [currentPosition, setCurrentPosition] = useState(0);
  const [isGeneratingSubtitles, setIsGeneratingSubtitles] = useState(false);

  useEffect(() => {
    loadVideoInfo();
  }, []);

  const loadVideoInfo = async () => {
    try {
      if (videoRef.current) {
        const status = await videoRef.current.getStatusAsync();
        if (status.isLoaded) {
          setVideoInfo({
            uri: videoUri,
            duration: status.durationMillis || 0,
            width: 720, // Default width, can be detected through other means
            height: 480, // Default height, can be detected through other means
            size: 0, // We don't have file size info from expo-av
            name: "Selected Video",
          });
        }
      }
      setIsLoading(false);
    } catch (error) {
      console.error("Error loading video info:", error);
      setIsLoading(false);
    }
  };

  const handlePlayPause = async () => {
    try {
      if (videoRef.current) {
        if (isPlaying) {
          await videoRef.current.pauseAsync();
        } else {
          await videoRef.current.playAsync();
        }
        setIsPlaying(!isPlaying);
      }
    } catch (error) {
      console.error("Error playing/pausing video:", error);
    }
  };

  const handleSeek = async (position) => {
    try {
      if (videoRef.current && videoInfo) {
        const seekPosition = (position / 100) * videoInfo.duration;
        await videoRef.current.setPositionAsync(seekPosition);
        setCurrentPosition(position);
      }
    } catch (error) {
      console.error("Error seeking video:", error);
    }
  };

  const generateSubtitles = async () => {
    setIsGeneratingSubtitles(true);

    // Simulate AI subtitle generation (for demo purposes)
    // In a real app, this would call the OpenAI Whisper API
    setTimeout(() => {
      const mockSubtitles = [
        {
          id: "1",
          startTime: 0,
          endTime: 3000,
          text: "Hello and welcome to our video!",
          style: {
            fontSize: 16,
            color: "#FFFFFF",
            backgroundColor: "rgba(0,0,0,0.8)",
            fontWeight: "normal",
          },
        },
        {
          id: "2",
          startTime: 3000,
          endTime: 7000,
          text: "This is a sample subtitle generated by AI.",
          style: {
            fontSize: 16,
            color: "#FFFFFF",
            backgroundColor: "rgba(0,0,0,0.8)",
            fontWeight: "normal",
          },
        },
        {
          id: "3",
          startTime: 7000,
          endTime: 12000,
          text: "You can edit and customize these subtitles.",
          style: {
            fontSize: 16,
            color: "#FFFFFF",
            backgroundColor: "rgba(0,0,0,0.8)",
            fontWeight: "normal",
          },
        },
      ];

      setIsGeneratingSubtitles(false);
      navigation.navigate("SubtitleEditor", {
        videoUri,
        subtitles: mockSubtitles,
      });
    }, 3000);
  };

  const formatTime = (milliseconds) => {
    const seconds = Math.floor(milliseconds / 1000);
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}:${remainingSeconds.toString().padStart(2, "0")}`;
  };

  if (isLoading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color="#4C1D95" />
          <Text style={styles.loadingText}>Loading video...</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.videoContainer}>
        <Video
          ref={videoRef}
          style={styles.video}
          source={{ uri: videoUri }}
          resizeMode={ResizeMode.CONTAIN}
          shouldPlay={false}
          isLooping={false}
          onLoad={loadVideoInfo}
          onPlaybackStatusUpdate={(status) => {
            if (status.isLoaded) {
              setCurrentPosition(
                ((status.positionMillis || 0) / (videoInfo?.duration || 1)) *
                  100
              );
            }
          }}
        />

        {/* Video Controls Overlay */}
        <View style={styles.controlsOverlay}>
          <TouchableOpacity style={styles.playButton} onPress={handlePlayPause}>
            <Ionicons
              name={isPlaying ? "pause" : "play"}
              size={40}
              color="#fff"
            />
          </TouchableOpacity>
        </View>
      </View>

      {/* Video Info */}
      {videoInfo && (
        <View style={styles.videoInfoContainer}>
          <Text style={styles.videoInfoTitle}>Video Information</Text>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Duration:</Text>
            <Text style={styles.infoValue}>
              {formatTime(videoInfo.duration)}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Resolution:</Text>
            <Text style={styles.infoValue}>
              {videoInfo.width} x {videoInfo.height}
            </Text>
          </View>
        </View>
      )}

      {/* Progress Bar */}
      <View style={styles.progressContainer}>
        <View style={styles.progressBar}>
          <View
            style={[styles.progressFill, { width: `${currentPosition}%` }]}
          />
        </View>
        <Text style={styles.timeText}>
          {videoInfo
            ? formatTime((currentPosition / 100) * videoInfo.duration)
            : "0:00"}{" "}
          / {videoInfo ? formatTime(videoInfo.duration) : "0:00"}
        </Text>
      </View>

      {/* Action Buttons */}
      <View style={styles.actionButtons}>
        <TouchableOpacity
          style={[
            styles.generateButton,
            isGeneratingSubtitles && styles.generateButtonDisabled,
          ]}
          onPress={generateSubtitles}
          disabled={isGeneratingSubtitles}
        >
          {isGeneratingSubtitles ? (
            <>
              <ActivityIndicator size="small" color="#fff" />
              <Text style={styles.generateButtonText}>
                Generating AI Subtitles...
              </Text>
            </>
          ) : (
            <>
              <Ionicons name="sparkles" size={20} color="#fff" />
              <Text style={styles.generateButtonText}>
                Generate AI Subtitles
              </Text>
            </>
          )}
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.manualButton}
          onPress={() =>
            navigation.navigate("SubtitleEditor", { videoUri, subtitles: [] })
          }
        >
          <Ionicons name="create" size={20} color="#4C1D95" />
          <Text style={styles.manualButtonText}>Manual Subtitles</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#6B7280",
  },
  videoContainer: {
    position: "relative",
    backgroundColor: "#000",
    margin: 20,
    borderRadius: 12,
    overflow: "hidden",
  },
  video: {
    width: screenWidth - 40,
    height: 200,
  },
  controlsOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  playButton: {
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 35,
    width: 70,
    height: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  videoInfoContainer: {
    backgroundColor: "#fff",
    margin: 20,
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  videoInfoTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 12,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  infoLabel: {
    fontSize: 14,
    color: "#6B7280",
  },
  infoValue: {
    fontSize: 14,
    color: "#1F2937",
    fontWeight: "500",
  },
  progressContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  progressBar: {
    height: 4,
    backgroundColor: "#E5E7EB",
    borderRadius: 2,
    marginBottom: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#4C1D95",
    borderRadius: 2,
  },
  timeText: {
    fontSize: 12,
    color: "#6B7280",
    textAlign: "center",
  },
  actionButtons: {
    paddingHorizontal: 20,
    gap: 12,
  },
  generateButton: {
    backgroundColor: "#4C1D95",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  generateButtonDisabled: {
    backgroundColor: "#9CA3AF",
  },
  generateButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  manualButton: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 2,
    borderColor: "#4C1D95",
  },
  manualButtonText: {
    color: "#4C1D95",
    fontSize: 16,
    fontWeight: "600",
  },
});

export default VideoEditorScreen;
